version: '2.1'

services:
  web:
    restart: always
    build: ./web/
    command: "./start.sh"
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    env_file: env
    working_dir: /data/web
    volumes:
      - ./web:/data/web
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web
  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - env
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  data:
    image: alpine:latest
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data/pgdata
    command: "true"
